name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y cmake build-essential
      - run: ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          name: deb
          path: build/*.deb
      - if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.deb
